language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang
    - os: osx
      compiler: clang

install:
  - mkdir ext
  - ./install_gtest.sh
script:
  - ./build.sh
